<a href="https://colab.research.google.com/github/narumirr/POLINES-KECERDASAN-BUATAN/blob/main/Jobsheet_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OPERASI MATEMATIKA, VEKTOR, DAN MATRIKS

# 1. Tipe Data Python

In [32]:
# a. Cek Tipe Data
print("Cek Tipe Data")
var = 123
print(type(var))

Cek Tipe Data
<class 'int'>


In [28]:
# b. Tipe data String
print("Cek Tipe String")
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

Cek Tipe String
<class 'str'>


In [31]:
# c. cek tipe data numerik
print("Cek Tipe Numerik")
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))

print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)
print()

Cek Tipe Numerik
<class 'float'>
345.0
379.5
34
12



In [33]:
# d. Tipe data Boolean
print("Cek Tipe Boolean")
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)
print()

Cek Tipe Boolean
False
False
True
True



In [34]:
# e. Tipe Data List
print("Cek Tipe List")
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))
print()

Cek Tipe List
['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4



# 2. Operasi matematika menggunakan python

In [45]:
# a. Mendapatkan nilai minimum dan maksimum
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

# b. mendapatkan nilai absolut
x = abs(-7.25)
print(x)

# c. import math
x = math.pow(4, 3)
print(x)

# d. Mendapatkan nilai akar
import  math
x = math.sqrt(64)
print(x)

# e. Mendapatkan nilai pembulatan
import  math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x, y)

# f. Mendapatkan nilai konstanta
import  math
x = math.pi
print(x)



5
18
7.25
64.0
8.0
2 1
3.141592653589793


# 3.	Menggunakan Fungsi MATH

In [40]:
import math

print("\n".join(map(str, [
    math.sin(0),
    math.cos(0),
    math.tan(0),
    math.log(10),
    math.log10(1),
    math.degrees(1),
    math.dist([1,2], [4,6]),
    math.factorial(5),
    math.fmod(10,3),
    math.isnan(5),
    math.gamma(5),
    math.perm(5,2)
])))

0.0
1.0
0.0
2.302585092994046
0.0
57.29577951308232
5.0
120
1.0
False
24.0
20


# 4. Operasi matriks dan vektor dengan python

In [15]:
# a. Membuat matriks di python
import  numpy  as  np
A  = np.array([[80, 30, 25],
[50, 20, 10]])
B  = np.array([[30, 60, 15],
[10, 30, 30]])
hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


In [16]:
# b. Melakukan operasi dot product
import  numpy  as  np
A  = np.array([10, 20, 15])
B  = np.array([16, 67, 35])
hasil = np.dot(A, B)
print(hasil)

2025


In [17]:
# c. Melakukan operasi cross product
import  numpy  as  np
A  = np.array([10, 20, 15])
B  = np.array([16, 67, 35])
Hasil = np.cross(A, B)
print(Hasil)

[-305 -110  350]


# TUGAS PRAKTIKUM

# 1. Hasil Perkalian

In [14]:
import numpy as np

# Definisi Matriks
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# a. A x B (Perkalian Matriks)
hasil_AB = np.matmul(A, B)
print("Hasil A x B:\n", hasil_AB)

# b. B . C
# Catatan: Secara matematis, perkalian matriks (dot product) mensyaratkan
# jumlah kolom matriks pertama sama dengan jumlah baris matriks kedua.
# Karena B (2x2) dan C (3x2), maka operasi B . C memerlukan transpose pada C (C.T)
# agar menjadi (2x2) * (2x3).
hasil_BC = np.dot(B, C)
print("Hasil B . C (Transpose):\n", hasil_BC)

Hasil A x B:
 [[7 2]
 [4 2]]
Hasil B . C (Transpose):
 [[ 0  2  3]
 [-3  1  3]]


# 2. Penghitungan Faktorial

In [ ]:
import math

# a. Menghitung 6!
faktorial_6 = math.factorial(6)
print("Nilai dari 6! adalah:", faktorial_6)

# b. Menghitung 8! / 5!
hasil_pembagian = math.factorial(8) / math.factorial(5)
print("Nilai dari 8! / 5! adalah:", hasil_pembagian)

Nilai dari 6! adalah: 720
Nilai dari 8! / 5! adalah: 336.0


# 3. Analisis Vektor 3D

In [ ]:
import numpy as np

# Definisi Vektor
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menentukan panjang (norm) masing-masing vektor
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Hasil perkalian titik (Dot Product) A.B
dot_product = np.dot(A, B)

# Hasil perkalian silang (Cross Product) AxB
cross_product = np.cross(A, B)

print(f"Panjang Vektor A: {panjang_A}")
print(f"Panjang Vektor B: {panjang_B}")
print(f"Hasil A.B (Dot Product): {dot_product}")
print(f"Hasil AxB (Cross Product): {cross_product}")

Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Hasil A.B (Dot Product): 58
Hasil AxB (Cross Product): [ 24  79 -51]
